[
  {
    "constraint_name": "2200_127141_1_not_null",
    "table_name": "admin_permissions",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "id IS NOT NULL"
  },
  {
    "constraint_name": "2200_127141_2_not_null",
    "table_name": "admin_permissions",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "admin_role_id IS NOT NULL"
  },
  {
    "constraint_name": "2200_127141_3_not_null",
    "table_name": "admin_permissions",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "permission IS NOT NULL"
  },
  {
    "constraint_name": "2200_127141_4_not_null",
    "table_name": "admin_permissions",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "created_at IS NOT NULL"
  },
  {
    "constraint_name": "2200_127141_5_not_null",
    "table_name": "admin_permissions",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "updated_at IS NOT NULL"
  },
  {
    "constraint_name": "admin_permissions_admin_role_id_fkey",
    "table_name": "admin_permissions",
    "constraint_type": "FOREIGN KEY",
    "column_name": "admin_role_id",
    "foreign_table_name": "admin_roles",
    "foreign_column_name": "id",
    "update_rule": "NO ACTION",
    "delete_rule": "NO ACTION",
    "check_clause": null
  },
  {
    "constraint_name": "admin_permissions_pkey",
    "table_name": "admin_permissions",
    "constraint_type": "PRIMARY KEY",
    "column_name": "id",
    "foreign_table_name": "admin_permissions",
    "foreign_column_name": "id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "unique_role_permission",
    "table_name": "admin_permissions",
    "constraint_type": "UNIQUE",
    "column_name": "permission",
    "foreign_table_name": "admin_permissions",
    "foreign_column_name": "admin_role_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "unique_role_permission",
    "table_name": "admin_permissions",
    "constraint_type": "UNIQUE",
    "column_name": "permission",
    "foreign_table_name": "admin_permissions",
    "foreign_column_name": "permission",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "unique_role_permission",
    "table_name": "admin_permissions",
    "constraint_type": "UNIQUE",
    "column_name": "admin_role_id",
    "foreign_table_name": "admin_permissions",
    "foreign_column_name": "permission",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "unique_role_permission",
    "table_name": "admin_permissions",
    "constraint_type": "UNIQUE",
    "column_name": "admin_role_id",
    "foreign_table_name": "admin_permissions",
    "foreign_column_name": "admin_role_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "2200_127149_1_not_null",
    "table_name": "admin_roles",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "id IS NOT NULL"
  },
  {
    "constraint_name": "2200_127149_2_not_null",
    "table_name": "admin_roles",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "player_id IS NOT NULL"
  },
  {
    "constraint_name": "2200_127149_3_not_null",
    "table_name": "admin_roles",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "created_at IS NOT NULL"
  },
  {
    "constraint_name": "2200_127149_4_not_null",
    "table_name": "admin_roles",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "updated_at IS NOT NULL"
  },
  {
    "constraint_name": "admin_roles_pkey",
    "table_name": "admin_roles",
    "constraint_type": "PRIMARY KEY",
    "column_name": "id",
    "foreign_table_name": "admin_roles",
    "foreign_column_name": "id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "admin_roles_player_id_fkey",
    "table_name": "admin_roles",
    "constraint_type": "FOREIGN KEY",
    "column_name": "player_id",
    "foreign_table_name": "players",
    "foreign_column_name": "id",
    "update_rule": "NO ACTION",
    "delete_rule": "NO ACTION",
    "check_clause": null
  },
  {
    "constraint_name": "unique_player_role",
    "table_name": "admin_roles",
    "constraint_type": "UNIQUE",
    "column_name": "player_id",
    "foreign_table_name": "admin_roles",
    "foreign_column_name": "player_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "2200_127155_1_not_null",
    "table_name": "balanced_team_assignments",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "game_id IS NOT NULL"
  },
  {
    "constraint_name": "2200_127155_2_not_null",
    "table_name": "balanced_team_assignments",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "team_assignments IS NOT NULL"
  },
  {
    "constraint_name": "2200_127155_3_not_null",
    "table_name": "balanced_team_assignments",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "created_at IS NOT NULL"
  },
  {
    "constraint_name": "balanced_team_assignments_game_id_fkey",
    "table_name": "balanced_team_assignments",
    "constraint_type": "FOREIGN KEY",
    "column_name": "game_id",
    "foreign_table_name": "games",
    "foreign_column_name": "id",
    "update_rule": "NO ACTION",
    "delete_rule": "CASCADE",
    "check_clause": null
  },
  {
    "constraint_name": "balanced_team_assignments_pkey",
    "table_name": "balanced_team_assignments",
    "constraint_type": "PRIMARY KEY",
    "column_name": "game_id",
    "foreign_table_name": "balanced_team_assignments",
    "foreign_column_name": "game_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "2200_137859_1_not_null",
    "table_name": "debug_logs",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "id IS NOT NULL"
  },
  {
    "constraint_name": "debug_logs_pkey",
    "table_name": "debug_logs",
    "constraint_type": "PRIMARY KEY",
    "column_name": "id",
    "foreign_table_name": "debug_logs",
    "foreign_column_name": "id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "2200_126996_11_not_null",
    "table_name": "game_registrations",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "selection_method IS NOT NULL"
  },
  {
    "constraint_name": "2200_126996_1_not_null",
    "table_name": "game_registrations",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "id IS NOT NULL"
  },
  {
    "constraint_name": "2200_126996_4_not_null",
    "table_name": "game_registrations",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "status IS NOT NULL"
  },
  {
    "constraint_name": "game_registrations_game_id_fkey",
    "table_name": "game_registrations",
    "constraint_type": "FOREIGN KEY",
    "column_name": "game_id",
    "foreign_table_name": "games",
    "foreign_column_name": "id",
    "update_rule": "NO ACTION",
    "delete_rule": "CASCADE",
    "check_clause": null
  },
  {
    "constraint_name": "game_registrations_paid_by_player_id_fkey",
    "table_name": "game_registrations",
    "constraint_type": "FOREIGN KEY",
    "column_name": "paid_by_player_id",
    "foreign_table_name": "players",
    "foreign_column_name": "id",
    "update_rule": "NO ACTION",
    "delete_rule": "NO ACTION",
    "check_clause": null
  },
  {
    "constraint_name": "game_registrations_payment_recipient_id_fkey",
    "table_name": "game_registrations",
    "constraint_type": "FOREIGN KEY",
    "column_name": "payment_recipient_id",
    "foreign_table_name": "players",
    "foreign_column_name": "id",
    "update_rule": "NO ACTION",
    "delete_rule": "NO ACTION",
    "check_clause": null
  },
  {
    "constraint_name": "game_registrations_payment_status_check",
    "table_name": "game_registrations",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": "game_registrations",
    "foreign_column_name": "payment_status",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "((payment_status = ANY (ARRAY['unpaid'::text, 'marked_paid'::text, 'admin_verified'::text])))"
  },
  {
    "constraint_name": "game_registrations_payment_verified_by_fkey",
    "table_name": "game_registrations",
    "constraint_type": "FOREIGN KEY",
    "column_name": "payment_verified_by",
    "foreign_table_name": "players",
    "foreign_column_name": "id",
    "update_rule": "NO ACTION",
    "delete_rule": "NO ACTION",
    "check_clause": null
  },
  {
    "constraint_name": "game_registrations_pkey",
    "table_name": "game_registrations",
    "constraint_type": "PRIMARY KEY",
    "column_name": "id",
    "foreign_table_name": "game_registrations",
    "foreign_column_name": "id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "game_registrations_player_id_fkey",
    "table_name": "game_registrations",
    "constraint_type": "FOREIGN KEY",
    "column_name": "player_id",
    "foreign_table_name": "players",
    "foreign_column_name": "id",
    "update_rule": "NO ACTION",
    "delete_rule": "CASCADE",
    "check_clause": null
  },
  {
    "constraint_name": "game_registrations_selection_method_check",
    "table_name": "game_registrations",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": "game_registrations",
    "foreign_column_name": "selection_method",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "((selection_method = ANY (ARRAY['merit'::text, 'random'::text, 'none'::text, 'slot_offer'::text])))"
  },
  {
    "constraint_name": "game_registrations_status_check",
    "table_name": "game_registrations",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": "game_registrations",
    "foreign_column_name": "status",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "((status = ANY (ARRAY['registered'::text, 'selected'::text, 'reserve'::text, 'dropped_out'::text])))"
  },
  {
    "constraint_name": "game_registrations_team_check",
    "table_name": "game_registrations",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": "game_registrations",
    "foreign_column_name": "team",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "((team = ANY (ARRAY['blue'::text, 'orange'::text])))"
  },
  {
    "constraint_name": "unique_game_player",
    "table_name": "game_registrations",
    "constraint_type": "UNIQUE",
    "column_name": "player_id",
    "foreign_table_name": "game_registrations",
    "foreign_column_name": "game_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "unique_game_player",
    "table_name": "game_registrations",
    "constraint_type": "UNIQUE",
    "column_name": "game_id",
    "foreign_table_name": "game_registrations",
    "foreign_column_name": "game_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "unique_game_player",
    "table_name": "game_registrations",
    "constraint_type": "UNIQUE",
    "column_name": "game_id",
    "foreign_table_name": "game_registrations",
    "foreign_column_name": "player_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "unique_game_player",
    "table_name": "game_registrations",
    "constraint_type": "UNIQUE",
    "column_name": "player_id",
    "foreign_table_name": "game_registrations",
    "foreign_column_name": "player_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "2200_127161_1_not_null",
    "table_name": "game_selections",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "id IS NOT NULL"
  },
  {
    "constraint_name": "2200_127161_2_not_null",
    "table_name": "game_selections",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "game_id IS NOT NULL"
  },
  {
    "constraint_name": "2200_127161_3_not_null",
    "table_name": "game_selections",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "selected_players IS NOT NULL"
  },
  {
    "constraint_name": "2200_127161_4_not_null",
    "table_name": "game_selections",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "reserve_players IS NOT NULL"
  },
  {
    "constraint_name": "2200_127161_6_not_null",
    "table_name": "game_selections",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "created_at IS NOT NULL"
  },
  {
    "constraint_name": "game_selections_game_id_fkey",
    "table_name": "game_selections",
    "constraint_type": "FOREIGN KEY",
    "column_name": "game_id",
    "foreign_table_name": "games",
    "foreign_column_name": "id",
    "update_rule": "NO ACTION",
    "delete_rule": "CASCADE",
    "check_clause": null
  },
  {
    "constraint_name": "game_selections_pkey",
    "table_name": "game_selections",
    "constraint_type": "PRIMARY KEY",
    "column_name": "id",
    "foreign_table_name": "game_selections",
    "foreign_column_name": "id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "2200_127168_11_not_null",
    "table_name": "games",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "random_slots IS NOT NULL"
  },
  {
    "constraint_name": "2200_127168_1_not_null",
    "table_name": "games",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "id IS NOT NULL"
  },
  {
    "constraint_name": "2200_127168_20_not_null",
    "table_name": "games",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "status IS NOT NULL"
  },
  {
    "constraint_name": "2200_127168_2_not_null",
    "table_name": "games",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "date IS NOT NULL"
  },
  {
    "constraint_name": "2200_127168_3_not_null",
    "table_name": "games",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "registration_window_start IS NOT NULL"
  },
  {
    "constraint_name": "2200_127168_4_not_null",
    "table_name": "games",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "registration_window_end IS NOT NULL"
  },
  {
    "constraint_name": "check_needs_completion",
    "table_name": "games",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": "games",
    "foreign_column_name": "score_blue",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "((((needs_completion = true) AND (created_at > '2024-11-28 00:00:00+00'::timestamp with time zone) AND ((score_blue IS NULL) OR (score_orange IS NULL) OR (outcome IS NULL))) OR (needs_completion = false)))"
  },
  {
    "constraint_name": "check_needs_completion",
    "table_name": "games",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": "games",
    "foreign_column_name": "score_orange",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "((((needs_completion = true) AND (created_at > '2024-11-28 00:00:00+00'::timestamp with time zone) AND ((score_blue IS NULL) OR (score_orange IS NULL) OR (outcome IS NULL))) OR (needs_completion = false)))"
  },
  {
    "constraint_name": "check_needs_completion",
    "table_name": "games",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": "games",
    "foreign_column_name": "created_at",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "((((needs_completion = true) AND (created_at > '2024-11-28 00:00:00+00'::timestamp with time zone) AND ((score_blue IS NULL) OR (score_orange IS NULL) OR (outcome IS NULL))) OR (needs_completion = false)))"
  },
  {
    "constraint_name": "check_needs_completion",
    "table_name": "games",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": "games",
    "foreign_column_name": "needs_completion",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "((((needs_completion = true) AND (created_at > '2024-11-28 00:00:00+00'::timestamp with time zone) AND ((score_blue IS NULL) OR (score_orange IS NULL) OR (outcome IS NULL))) OR (needs_completion = false)))"
  },
  {
    "constraint_name": "check_needs_completion",
    "table_name": "games",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": "games",
    "foreign_column_name": "outcome",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "((((needs_completion = true) AND (created_at > '2024-11-28 00:00:00+00'::timestamp with time zone) AND ((score_blue IS NULL) OR (score_orange IS NULL) OR (outcome IS NULL))) OR (needs_completion = false)))"
  },
  {
    "constraint_name": "games_outcome_check",
    "table_name": "games",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": "games",
    "foreign_column_name": "outcome",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "((outcome = ANY (ARRAY['blue_win'::text, 'orange_win'::text, 'draw'::text])))"
  },
  {
    "constraint_name": "games_pkey",
    "table_name": "games",
    "constraint_type": "PRIMARY KEY",
    "column_name": "id",
    "foreign_table_name": "games",
    "foreign_column_name": "id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "games_venue_id_fkey",
    "table_name": "games",
    "constraint_type": "FOREIGN KEY",
    "column_name": "venue_id",
    "foreign_table_name": "venues",
    "foreign_column_name": "id",
    "update_rule": "NO ACTION",
    "delete_rule": "NO ACTION",
    "check_clause": null
  },
  {
    "constraint_name": "valid_dates",
    "table_name": "games",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": "games",
    "foreign_column_name": "registration_window_start",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "(((registration_window_start < registration_window_end) AND (registration_window_end <= date)))"
  },
  {
    "constraint_name": "valid_dates",
    "table_name": "games",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": "games",
    "foreign_column_name": "registration_window_end",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "(((registration_window_start < registration_window_end) AND (registration_window_end <= date)))"
  },
  {
    "constraint_name": "valid_dates",
    "table_name": "games",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": "games",
    "foreign_column_name": "date",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "(((registration_window_start < registration_window_end) AND (registration_window_end <= date)))"
  },
  {
    "constraint_name": "valid_score",
    "table_name": "games",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": "games",
    "foreign_column_name": "score_orange",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "((((score_blue IS NULL) AND (score_orange IS NULL)) OR ((score_blue IS NOT NULL) AND (score_orange IS NOT NULL))))"
  },
  {
    "constraint_name": "valid_score",
    "table_name": "games",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": "games",
    "foreign_column_name": "score_blue",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "((((score_blue IS NULL) AND (score_orange IS NULL)) OR ((score_blue IS NOT NULL) AND (score_orange IS NOT NULL))))"
  },
  {
    "constraint_name": "2200_127186_1_not_null",
    "table_name": "notifications",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "id IS NOT NULL"
  },
  {
    "constraint_name": "2200_127186_2_not_null",
    "table_name": "notifications",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "player_id IS NOT NULL"
  },
  {
    "constraint_name": "2200_127186_3_not_null",
    "table_name": "notifications",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "type IS NOT NULL"
  },
  {
    "constraint_name": "2200_127186_4_not_null",
    "table_name": "notifications",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "message IS NOT NULL"
  },
  {
    "constraint_name": "notifications_pkey",
    "table_name": "notifications",
    "constraint_type": "PRIMARY KEY",
    "column_name": "id",
    "foreign_table_name": "notifications",
    "foreign_column_name": "id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "notifications_player_id_fkey",
    "table_name": "notifications",
    "constraint_type": "FOREIGN KEY",
    "column_name": "player_id",
    "foreign_table_name": "players",
    "foreign_column_name": "id",
    "update_rule": "NO ACTION",
    "delete_rule": "NO ACTION",
    "check_clause": null
  },
  {
    "constraint_name": "notifications_type_check",
    "table_name": "notifications",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": "notifications",
    "foreign_column_name": "type",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "((type = ANY (ARRAY['game_created'::text, 'game_cancelled'::text, 'team_announced'::text, 'game_reminder'::text, 'payment_request'::text, 'payment_confirmed'::text, 'registration_confirmed'::text, 'registration_removed'::text, 'bonus_earned'::text, 'penalty_earned'::text, 'system_announcement'::text, 'slot_offer'::text])))"
  },
  {
    "constraint_name": "2200_127195_1_not_null",
    "table_name": "payment_presets",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "id IS NOT NULL"
  },
  {
    "constraint_name": "2200_127195_2_not_null",
    "table_name": "payment_presets",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "name IS NOT NULL"
  },
  {
    "constraint_name": "2200_127195_3_not_null",
    "table_name": "payment_presets",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "player_id IS NOT NULL"
  },
  {
    "constraint_name": "payment_presets_pkey",
    "table_name": "payment_presets",
    "constraint_type": "PRIMARY KEY",
    "column_name": "id",
    "foreign_table_name": "payment_presets",
    "foreign_column_name": "id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "payment_presets_player_id_fkey",
    "table_name": "payment_presets",
    "constraint_type": "FOREIGN KEY",
    "column_name": "player_id",
    "foreign_table_name": "players",
    "foreign_column_name": "id",
    "update_rule": "NO ACTION",
    "delete_rule": "NO ACTION",
    "check_clause": null
  },
  {
    "constraint_name": "2200_127202_1_not_null",
    "table_name": "player_penalties",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "id IS NOT NULL"
  },
  {
    "constraint_name": "2200_127202_2_not_null",
    "table_name": "player_penalties",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "player_id IS NOT NULL"
  },
  {
    "constraint_name": "2200_127202_3_not_null",
    "table_name": "player_penalties",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "game_id IS NOT NULL"
  },
  {
    "constraint_name": "2200_127202_4_not_null",
    "table_name": "player_penalties",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "penalty_type IS NOT NULL"
  },
  {
    "constraint_name": "2200_127202_6_not_null",
    "table_name": "player_penalties",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "expires_after_games IS NOT NULL"
  },
  {
    "constraint_name": "2200_127202_7_not_null",
    "table_name": "player_penalties",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "games_remaining IS NOT NULL"
  },
  {
    "constraint_name": "player_penalties_game_id_fkey",
    "table_name": "player_penalties",
    "constraint_type": "FOREIGN KEY",
    "column_name": "game_id",
    "foreign_table_name": "games",
    "foreign_column_name": "id",
    "update_rule": "NO ACTION",
    "delete_rule": "CASCADE",
    "check_clause": null
  },
  {
    "constraint_name": "player_penalties_penalty_type_check",
    "table_name": "player_penalties",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": "player_penalties",
    "foreign_column_name": "penalty_type",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "((penalty_type = 'SAME_DAY_DROPOUT'::text))"
  },
  {
    "constraint_name": "player_penalties_pkey",
    "table_name": "player_penalties",
    "constraint_type": "PRIMARY KEY",
    "column_name": "id",
    "foreign_table_name": "player_penalties",
    "foreign_column_name": "id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "player_penalties_player_id_fkey",
    "table_name": "player_penalties",
    "constraint_type": "FOREIGN KEY",
    "column_name": "player_id",
    "foreign_table_name": "players",
    "foreign_column_name": "id",
    "update_rule": "NO ACTION",
    "delete_rule": "NO ACTION",
    "check_clause": null
  },
  {
    "constraint_name": "player_penalties_player_id_game_id_penalty_type_key",
    "table_name": "player_penalties",
    "constraint_type": "UNIQUE",
    "column_name": "penalty_type",
    "foreign_table_name": "player_penalties",
    "foreign_column_name": "player_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "player_penalties_player_id_game_id_penalty_type_key",
    "table_name": "player_penalties",
    "constraint_type": "UNIQUE",
    "column_name": "game_id",
    "foreign_table_name": "player_penalties",
    "foreign_column_name": "penalty_type",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "player_penalties_player_id_game_id_penalty_type_key",
    "table_name": "player_penalties",
    "constraint_type": "UNIQUE",
    "column_name": "player_id",
    "foreign_table_name": "player_penalties",
    "foreign_column_name": "player_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "player_penalties_player_id_game_id_penalty_type_key",
    "table_name": "player_penalties",
    "constraint_type": "UNIQUE",
    "column_name": "player_id",
    "foreign_table_name": "player_penalties",
    "foreign_column_name": "game_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "player_penalties_player_id_game_id_penalty_type_key",
    "table_name": "player_penalties",
    "constraint_type": "UNIQUE",
    "column_name": "game_id",
    "foreign_table_name": "player_penalties",
    "foreign_column_name": "game_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "player_penalties_player_id_game_id_penalty_type_key",
    "table_name": "player_penalties",
    "constraint_type": "UNIQUE",
    "column_name": "penalty_type",
    "foreign_table_name": "player_penalties",
    "foreign_column_name": "game_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "player_penalties_player_id_game_id_penalty_type_key",
    "table_name": "player_penalties",
    "constraint_type": "UNIQUE",
    "column_name": "penalty_type",
    "foreign_table_name": "player_penalties",
    "foreign_column_name": "penalty_type",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "player_penalties_player_id_game_id_penalty_type_key",
    "table_name": "player_penalties",
    "constraint_type": "UNIQUE",
    "column_name": "player_id",
    "foreign_table_name": "player_penalties",
    "foreign_column_name": "penalty_type",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "player_penalties_player_id_game_id_penalty_type_key",
    "table_name": "player_penalties",
    "constraint_type": "UNIQUE",
    "column_name": "game_id",
    "foreign_table_name": "player_penalties",
    "foreign_column_name": "player_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "2200_127212_1_not_null",
    "table_name": "player_ratings",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "id IS NOT NULL"
  },
  {
    "constraint_name": "2200_127212_2_not_null",
    "table_name": "player_ratings",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "rater_id IS NOT NULL"
  },
  {
    "constraint_name": "2200_127212_3_not_null",
    "table_name": "player_ratings",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "rated_player_id IS NOT NULL"
  },
  {
    "constraint_name": "cannot_rate_self",
    "table_name": "player_ratings",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": "player_ratings",
    "foreign_column_name": "rater_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "((rater_id <> rated_player_id))"
  },
  {
    "constraint_name": "cannot_rate_self",
    "table_name": "player_ratings",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": "player_ratings",
    "foreign_column_name": "rated_player_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "((rater_id <> rated_player_id))"
  },
  {
    "constraint_name": "player_ratings_attack_rating_check",
    "table_name": "player_ratings",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": "player_ratings",
    "foreign_column_name": "attack_rating",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "(((attack_rating >= (0)::numeric) AND (attack_rating <= (10)::numeric)))"
  },
  {
    "constraint_name": "player_ratings_defense_rating_check",
    "table_name": "player_ratings",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": "player_ratings",
    "foreign_column_name": "defense_rating",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "(((defense_rating >= (0)::numeric) AND (defense_rating <= (10)::numeric)))"
  },
  {
    "constraint_name": "player_ratings_pkey",
    "table_name": "player_ratings",
    "constraint_type": "PRIMARY KEY",
    "column_name": "id",
    "foreign_table_name": "player_ratings",
    "foreign_column_name": "id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "player_ratings_rated_player_id_fkey",
    "table_name": "player_ratings",
    "constraint_type": "FOREIGN KEY",
    "column_name": "rated_player_id",
    "foreign_table_name": "players",
    "foreign_column_name": "id",
    "update_rule": "NO ACTION",
    "delete_rule": "NO ACTION",
    "check_clause": null
  },
  {
    "constraint_name": "player_ratings_rater_id_fkey",
    "table_name": "player_ratings",
    "constraint_type": "FOREIGN KEY",
    "column_name": "rater_id",
    "foreign_table_name": "players",
    "foreign_column_name": "id",
    "update_rule": "NO ACTION",
    "delete_rule": "NO ACTION",
    "check_clause": null
  },
  {
    "constraint_name": "unique_rating_pair",
    "table_name": "player_ratings",
    "constraint_type": "UNIQUE",
    "column_name": "rated_player_id",
    "foreign_table_name": "player_ratings",
    "foreign_column_name": "rated_player_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "unique_rating_pair",
    "table_name": "player_ratings",
    "constraint_type": "UNIQUE",
    "column_name": "rater_id",
    "foreign_table_name": "player_ratings",
    "foreign_column_name": "rated_player_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "unique_rating_pair",
    "table_name": "player_ratings",
    "constraint_type": "UNIQUE",
    "column_name": "rated_player_id",
    "foreign_table_name": "player_ratings",
    "foreign_column_name": "rater_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "unique_rating_pair",
    "table_name": "player_ratings",
    "constraint_type": "UNIQUE",
    "column_name": "rater_id",
    "foreign_table_name": "player_ratings",
    "foreign_column_name": "rater_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "2200_134426_1_not_null",
    "table_name": "player_xp",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "player_id IS NOT NULL"
  },
  {
    "constraint_name": "2200_134426_2_not_null",
    "table_name": "player_xp",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "xp IS NOT NULL"
  },
  {
    "constraint_name": "player_xp_pkey",
    "table_name": "player_xp",
    "constraint_type": "PRIMARY KEY",
    "column_name": "player_id",
    "foreign_table_name": "player_xp",
    "foreign_column_name": "player_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "player_xp_player_id_fkey",
    "table_name": "player_xp",
    "constraint_type": "FOREIGN KEY",
    "column_name": "player_id",
    "foreign_table_name": "players",
    "foreign_column_name": "id",
    "update_rule": "NO ACTION",
    "delete_rule": "NO ACTION",
    "check_clause": null
  },
  {
    "constraint_name": "player_xp_xp_check",
    "table_name": "player_xp",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": "player_xp",
    "foreign_column_name": "xp",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "((xp >= 0))"
  },
  {
    "constraint_name": "2200_127223_1_not_null",
    "table_name": "players",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "id IS NOT NULL"
  },
  {
    "constraint_name": "2200_127223_3_not_null",
    "table_name": "players",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "friendly_name IS NOT NULL"
  },
  {
    "constraint_name": "players_friendly_name_test_unique",
    "table_name": "players",
    "constraint_type": "UNIQUE",
    "column_name": "is_test_user",
    "foreign_table_name": "players",
    "foreign_column_name": "is_test_user",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "players_friendly_name_test_unique",
    "table_name": "players",
    "constraint_type": "UNIQUE",
    "column_name": "is_test_user",
    "foreign_table_name": "players",
    "foreign_column_name": "friendly_name",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "players_friendly_name_test_unique",
    "table_name": "players",
    "constraint_type": "UNIQUE",
    "column_name": "friendly_name",
    "foreign_table_name": "players",
    "foreign_column_name": "is_test_user",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "players_friendly_name_test_unique",
    "table_name": "players",
    "constraint_type": "UNIQUE",
    "column_name": "friendly_name",
    "foreign_table_name": "players",
    "foreign_column_name": "friendly_name",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "players_pkey",
    "table_name": "players",
    "constraint_type": "PRIMARY KEY",
    "column_name": "id",
    "foreign_table_name": "players",
    "foreign_column_name": "id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "players_user_id_fkey",
    "table_name": "players",
    "constraint_type": "FOREIGN KEY",
    "column_name": "user_id",
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": "NO ACTION",
    "delete_rule": "NO ACTION",
    "check_clause": null
  },
  {
    "constraint_name": "players_whatsapp_group_member_check",
    "table_name": "players",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": "players",
    "foreign_column_name": "whatsapp_group_member",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "((whatsapp_group_member = ANY (ARRAY['Yes'::text, 'No'::text, 'Proxy'::text])))"
  },
  {
    "constraint_name": "players_whatsapp_mobile_number_check",
    "table_name": "players",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": "players",
    "foreign_column_name": "whatsapp_mobile_number",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "((whatsapp_mobile_number ~ '^\\+[1-9]\\d{1,14}$'::text))"
  },
  {
    "constraint_name": "valid_win_rate",
    "table_name": "players",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": "players",
    "foreign_column_name": "win_rate",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "(((win_rate >= (0)::numeric) AND (win_rate <= (100)::numeric)))"
  },
  {
    "constraint_name": "2200_181856_1_not_null",
    "table_name": "registration_locks",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "id IS NOT NULL"
  },
  {
    "constraint_name": "2200_181856_3_not_null",
    "table_name": "registration_locks",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "locked_at IS NOT NULL"
  },
  {
    "constraint_name": "2200_181856_4_not_null",
    "table_name": "registration_locks",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "locked_until IS NOT NULL"
  },
  {
    "constraint_name": "registration_locks_game_id_fkey",
    "table_name": "registration_locks",
    "constraint_type": "FOREIGN KEY",
    "column_name": "game_id",
    "foreign_table_name": "games",
    "foreign_column_name": "id",
    "update_rule": "NO ACTION",
    "delete_rule": "NO ACTION",
    "check_clause": null
  },
  {
    "constraint_name": "registration_locks_game_id_key",
    "table_name": "registration_locks",
    "constraint_type": "UNIQUE",
    "column_name": "game_id",
    "foreign_table_name": "registration_locks",
    "foreign_column_name": "game_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "registration_locks_pkey",
    "table_name": "registration_locks",
    "constraint_type": "PRIMARY KEY",
    "column_name": "id",
    "foreign_table_name": "registration_locks",
    "foreign_column_name": "id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "2200_158856_1_not_null",
    "table_name": "reserve_xp_transactions",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "id IS NOT NULL"
  },
  {
    "constraint_name": "2200_158856_2_not_null",
    "table_name": "reserve_xp_transactions",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "player_id IS NOT NULL"
  },
  {
    "constraint_name": "2200_158856_3_not_null",
    "table_name": "reserve_xp_transactions",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "game_id IS NOT NULL"
  },
  {
    "constraint_name": "2200_158856_4_not_null",
    "table_name": "reserve_xp_transactions",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "xp_amount IS NOT NULL"
  },
  {
    "constraint_name": "2200_158856_5_not_null",
    "table_name": "reserve_xp_transactions",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "transaction_type IS NOT NULL"
  },
  {
    "constraint_name": "reserve_xp_transactions_game_id_fkey",
    "table_name": "reserve_xp_transactions",
    "constraint_type": "FOREIGN KEY",
    "column_name": "game_id",
    "foreign_table_name": "games",
    "foreign_column_name": "id",
    "update_rule": "NO ACTION",
    "delete_rule": "CASCADE",
    "check_clause": null
  },
  {
    "constraint_name": "reserve_xp_transactions_pkey",
    "table_name": "reserve_xp_transactions",
    "constraint_type": "PRIMARY KEY",
    "column_name": "id",
    "foreign_table_name": "reserve_xp_transactions",
    "foreign_column_name": "id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "reserve_xp_transactions_player_id_fkey",
    "table_name": "reserve_xp_transactions",
    "constraint_type": "FOREIGN KEY",
    "column_name": "player_id",
    "foreign_table_name": "players",
    "foreign_column_name": "id",
    "update_rule": "NO ACTION",
    "delete_rule": "NO ACTION",
    "check_clause": null
  },
  {
    "constraint_name": "reserve_xp_transactions_player_id_game_id_transaction_type_key",
    "table_name": "reserve_xp_transactions",
    "constraint_type": "UNIQUE",
    "column_name": "game_id",
    "foreign_table_name": "reserve_xp_transactions",
    "foreign_column_name": "transaction_type",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "reserve_xp_transactions_player_id_game_id_transaction_type_key",
    "table_name": "reserve_xp_transactions",
    "constraint_type": "UNIQUE",
    "column_name": "transaction_type",
    "foreign_table_name": "reserve_xp_transactions",
    "foreign_column_name": "transaction_type",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "reserve_xp_transactions_player_id_game_id_transaction_type_key",
    "table_name": "reserve_xp_transactions",
    "constraint_type": "UNIQUE",
    "column_name": "transaction_type",
    "foreign_table_name": "reserve_xp_transactions",
    "foreign_column_name": "game_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "reserve_xp_transactions_player_id_game_id_transaction_type_key",
    "table_name": "reserve_xp_transactions",
    "constraint_type": "UNIQUE",
    "column_name": "transaction_type",
    "foreign_table_name": "reserve_xp_transactions",
    "foreign_column_name": "player_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "reserve_xp_transactions_player_id_game_id_transaction_type_key",
    "table_name": "reserve_xp_transactions",
    "constraint_type": "UNIQUE",
    "column_name": "game_id",
    "foreign_table_name": "reserve_xp_transactions",
    "foreign_column_name": "game_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "reserve_xp_transactions_player_id_game_id_transaction_type_key",
    "table_name": "reserve_xp_transactions",
    "constraint_type": "UNIQUE",
    "column_name": "game_id",
    "foreign_table_name": "reserve_xp_transactions",
    "foreign_column_name": "player_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "reserve_xp_transactions_player_id_game_id_transaction_type_key",
    "table_name": "reserve_xp_transactions",
    "constraint_type": "UNIQUE",
    "column_name": "player_id",
    "foreign_table_name": "reserve_xp_transactions",
    "foreign_column_name": "transaction_type",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "reserve_xp_transactions_player_id_game_id_transaction_type_key",
    "table_name": "reserve_xp_transactions",
    "constraint_type": "UNIQUE",
    "column_name": "player_id",
    "foreign_table_name": "reserve_xp_transactions",
    "foreign_column_name": "game_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "reserve_xp_transactions_player_id_game_id_transaction_type_key",
    "table_name": "reserve_xp_transactions",
    "constraint_type": "UNIQUE",
    "column_name": "player_id",
    "foreign_table_name": "reserve_xp_transactions",
    "foreign_column_name": "player_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "reserve_xp_transactions_transaction_type_check",
    "table_name": "reserve_xp_transactions",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": "reserve_xp_transactions",
    "foreign_column_name": "transaction_type",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "((transaction_type = ANY (ARRAY['RESERVE_REWARD'::text, 'SLOT_DECLINE_PENALTY'::text])))"
  },
  {
    "constraint_name": "2200_127245_1_not_null",
    "table_name": "slot_offers",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "id IS NOT NULL"
  },
  {
    "constraint_name": "2200_127245_2_not_null",
    "table_name": "slot_offers",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "game_id IS NOT NULL"
  },
  {
    "constraint_name": "2200_127245_3_not_null",
    "table_name": "slot_offers",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "player_id IS NOT NULL"
  },
  {
    "constraint_name": "2200_127245_4_not_null",
    "table_name": "slot_offers",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "status IS NOT NULL"
  },
  {
    "constraint_name": "2200_127245_5_not_null",
    "table_name": "slot_offers",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "offered_at IS NOT NULL"
  },
  {
    "constraint_name": "2200_127245_7_not_null",
    "table_name": "slot_offers",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "created_at IS NOT NULL"
  },
  {
    "constraint_name": "2200_127245_8_not_null",
    "table_name": "slot_offers",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "updated_at IS NOT NULL"
  },
  {
    "constraint_name": "slot_offers_admin_id_fkey",
    "table_name": "slot_offers",
    "constraint_type": "FOREIGN KEY",
    "column_name": "admin_id",
    "foreign_table_name": "players",
    "foreign_column_name": "id",
    "update_rule": "NO ACTION",
    "delete_rule": "NO ACTION",
    "check_clause": null
  },
  {
    "constraint_name": "slot_offers_dropped_out_player_id_fkey",
    "table_name": "slot_offers",
    "constraint_type": "FOREIGN KEY",
    "column_name": "dropped_out_player_id",
    "foreign_table_name": "players",
    "foreign_column_name": "id",
    "update_rule": "NO ACTION",
    "delete_rule": "NO ACTION",
    "check_clause": null
  },
  {
    "constraint_name": "slot_offers_game_id_fkey",
    "table_name": "slot_offers",
    "constraint_type": "FOREIGN KEY",
    "column_name": "game_id",
    "foreign_table_name": "games",
    "foreign_column_name": "id",
    "update_rule": "NO ACTION",
    "delete_rule": "CASCADE",
    "check_clause": null
  },
  {
    "constraint_name": "slot_offers_game_id_player_id_status_key",
    "table_name": "slot_offers",
    "constraint_type": "UNIQUE",
    "column_name": "game_id",
    "foreign_table_name": "slot_offers",
    "foreign_column_name": "player_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "slot_offers_game_id_player_id_status_key",
    "table_name": "slot_offers",
    "constraint_type": "UNIQUE",
    "column_name": "status",
    "foreign_table_name": "slot_offers",
    "foreign_column_name": "player_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "slot_offers_game_id_player_id_status_key",
    "table_name": "slot_offers",
    "constraint_type": "UNIQUE",
    "column_name": "status",
    "foreign_table_name": "slot_offers",
    "foreign_column_name": "status",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "slot_offers_game_id_player_id_status_key",
    "table_name": "slot_offers",
    "constraint_type": "UNIQUE",
    "column_name": "player_id",
    "foreign_table_name": "slot_offers",
    "foreign_column_name": "status",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "slot_offers_game_id_player_id_status_key",
    "table_name": "slot_offers",
    "constraint_type": "UNIQUE",
    "column_name": "player_id",
    "foreign_table_name": "slot_offers",
    "foreign_column_name": "player_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "slot_offers_game_id_player_id_status_key",
    "table_name": "slot_offers",
    "constraint_type": "UNIQUE",
    "column_name": "game_id",
    "foreign_table_name": "slot_offers",
    "foreign_column_name": "game_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "slot_offers_game_id_player_id_status_key",
    "table_name": "slot_offers",
    "constraint_type": "UNIQUE",
    "column_name": "game_id",
    "foreign_table_name": "slot_offers",
    "foreign_column_name": "status",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "slot_offers_game_id_player_id_status_key",
    "table_name": "slot_offers",
    "constraint_type": "UNIQUE",
    "column_name": "status",
    "foreign_table_name": "slot_offers",
    "foreign_column_name": "game_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "slot_offers_game_id_player_id_status_key",
    "table_name": "slot_offers",
    "constraint_type": "UNIQUE",
    "column_name": "player_id",
    "foreign_table_name": "slot_offers",
    "foreign_column_name": "game_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "slot_offers_pkey",
    "table_name": "slot_offers",
    "constraint_type": "PRIMARY KEY",
    "column_name": "id",
    "foreign_table_name": "slot_offers",
    "foreign_column_name": "id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "slot_offers_player_id_fkey",
    "table_name": "slot_offers",
    "constraint_type": "FOREIGN KEY",
    "column_name": "player_id",
    "foreign_table_name": "players",
    "foreign_column_name": "id",
    "update_rule": "NO ACTION",
    "delete_rule": "NO ACTION",
    "check_clause": null
  },
  {
    "constraint_name": "2200_181914_1_not_null",
    "table_name": "team_announcement_locks",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "id IS NOT NULL"
  },
  {
    "constraint_name": "2200_181914_3_not_null",
    "table_name": "team_announcement_locks",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "locked_at IS NOT NULL"
  },
  {
    "constraint_name": "2200_181914_4_not_null",
    "table_name": "team_announcement_locks",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "locked_until IS NOT NULL"
  },
  {
    "constraint_name": "team_announcement_locks_game_id_fkey",
    "table_name": "team_announcement_locks",
    "constraint_type": "FOREIGN KEY",
    "column_name": "game_id",
    "foreign_table_name": "games",
    "foreign_column_name": "id",
    "update_rule": "NO ACTION",
    "delete_rule": "NO ACTION",
    "check_clause": null
  },
  {
    "constraint_name": "team_announcement_locks_game_id_key",
    "table_name": "team_announcement_locks",
    "constraint_type": "UNIQUE",
    "column_name": "game_id",
    "foreign_table_name": "team_announcement_locks",
    "foreign_column_name": "game_id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "team_announcement_locks_pkey",
    "table_name": "team_announcement_locks",
    "constraint_type": "PRIMARY KEY",
    "column_name": "id",
    "foreign_table_name": "team_announcement_locks",
    "foreign_column_name": "id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "2200_127254_11_not_null",
    "table_name": "venue_presets",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "team_announcement_hours IS NOT NULL"
  },
  {
    "constraint_name": "2200_127254_1_not_null",
    "table_name": "venue_presets",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "id IS NOT NULL"
  },
  {
    "constraint_name": "2200_127254_3_not_null",
    "table_name": "venue_presets",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "name IS NOT NULL"
  },
  {
    "constraint_name": "2200_127254_4_not_null",
    "table_name": "venue_presets",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "day_of_week IS NOT NULL"
  },
  {
    "constraint_name": "2200_127254_5_not_null",
    "table_name": "venue_presets",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "start_time IS NOT NULL"
  },
  {
    "constraint_name": "2200_127254_6_not_null",
    "table_name": "venue_presets",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "registration_hours_before IS NOT NULL"
  },
  {
    "constraint_name": "2200_127254_7_not_null",
    "table_name": "venue_presets",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "registration_hours_until IS NOT NULL"
  },
  {
    "constraint_name": "venue_presets_pkey",
    "table_name": "venue_presets",
    "constraint_type": "PRIMARY KEY",
    "column_name": "id",
    "foreign_table_name": "venue_presets",
    "foreign_column_name": "id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  },
  {
    "constraint_name": "venue_presets_venue_id_fkey",
    "table_name": "venue_presets",
    "constraint_type": "FOREIGN KEY",
    "column_name": "venue_id",
    "foreign_table_name": "venues",
    "foreign_column_name": "id",
    "update_rule": "NO ACTION",
    "delete_rule": "CASCADE",
    "check_clause": null
  },
  {
    "constraint_name": "2200_127266_1_not_null",
    "table_name": "venues",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "id IS NOT NULL"
  },
  {
    "constraint_name": "2200_127266_2_not_null",
    "table_name": "venues",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "name IS NOT NULL"
  },
  {
    "constraint_name": "2200_127266_3_not_null",
    "table_name": "venues",
    "constraint_type": "CHECK",
    "column_name": null,
    "foreign_table_name": null,
    "foreign_column_name": null,
    "update_rule": null,
    "delete_rule": null,
    "check_clause": "address IS NOT NULL"
  },
  {
    "constraint_name": "venues_pkey",
    "table_name": "venues",
    "constraint_type": "PRIMARY KEY",
    "column_name": "id",
    "foreign_table_name": "venues",
    "foreign_column_name": "id",
    "update_rule": null,
    "delete_rule": null,
    "check_clause": null
  }
]