name: Check Slot Offers

on:
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes

jobs:
  check-slot-offers:
    runs-on: ubuntu-latest
    steps:
      - name: Call Edge Function
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
            "${{ secrets.SUPABASE_URL }}/functions/v1/check-slot-offers"
